version: "3.9"

services:
  api:
    container_name: project_api
    build: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/prueba_jeloy
      - JWT_SECRET=supersecret
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:6
    container_name: project_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: miapp
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: project_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongo

volumes:
  mongo_data:
